/**
 * Gap-inventory status-refresh/check tooling (bead fabric-cb4e1df8).
 *
 * docs/gap-analysis.md is the documented open-gap inventory; the 2026-09-28
 * reconciliation replaced its hand-maintained open-bead counts with a generated
 * inventory block plus scripts/gap-inventory-check.mjs, the repeatable
 * status-refresh/check. These tests pin the tool's contract on fixture
 * checkpoints/documents, and lint the real document structurally (block parses,
 * every cited bead id exists in the store) without comparing live statuses —
 * so routine bead closures by other workers never redden the shared suite.
 *
 * Exit-code contract (asserted here so drift is actionable, not silent):
 *   0 in sync · 1 drift or unknown-id citation · 2 structural · 3 no store source
 */

import { describe, it, expect, afterEach } from 'vitest';
import { exec } from 'node:child_process';
import { promisify } from 'node:util';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';

const execAsync = promisify(exec);

// tests/gapInventoryCheck.test.ts → repo root is two levels up.
const repoRoot = fileURLToPath(new URL('..', import.meta.url));
const SCRIPT = resolve(repoRoot, 'scripts', 'gap-inventory-check.mjs');
const REAL_DOC = resolve(repoRoot, 'docs', 'gap-analysis.md');
const REAL_CHECKPOINT = resolve(repoRoot, '.beads', 'checkpoint');

interface RunResult {
  code: number;
  stdout: string;
  stderr: string;
}

async function runScript(args: string[], cwd: string = repoRoot): Promise<RunResult> {
  const quoted = args.map((a) => JSON.stringify(a)).join(' ');
  try {
    const { stdout, stderr } = await execAsync(`node ${JSON.stringify(SCRIPT)} ${quoted}`, {
      cwd,
      encoding: 'utf8',
    });
    return { code: 0, stdout, stderr };
  } catch (err) {
    const e = err as { code?: number; stdout?: string; stderr?: string };
    return { code: e.code ?? -1, stdout: e.stdout ?? '', stderr: e.stderr ?? '' };
  }
}

interface FixtureBead {
  id: string;
  status: string;
  title: string;
  priority?: number;
}

/** Fixture checkpoint in the real layout: current.json → active_root → objects/<sha>.jsonl */
function writeCheckpoint(checkpointDir: string, beads: FixtureBead[], objectFileName = 'a'.repeat(64)): void {
  const objectsDir = join(checkpointDir, 'objects');
  mkdirSync(objectsDir, { recursive: true });
  const lines = beads.map((b) =>
    JSON.stringify({
      record_type: 'issue',
      issue: { id: b.id, base_status: b.status, title: b.title, priority: b.priority ?? 2 },
    }),
  );
  writeFileSync(join(objectsDir, `${objectFileName}.jsonl`), `${lines.join('\n')}\n`);
  writeFileSync(
    join(checkpointDir, 'current.json'),
    JSON.stringify({ active_root: { path: `objects/${objectFileName}.jsonl`, sha256: 'fixture' } }),
  );
}

function inventoryBlock(rows: string[]): string {
  return [
    '<!-- gap-inventory:begin (generated by scripts/gap-inventory-check.mjs — do not hand-edit; refresh: node scripts/gap-inventory-check.mjs --fix)',
    'bead_id\tstatus\tpriority\ttitle',
    ...rows,
    'gap-inventory:end -->',
  ].join('\n');
}

function row(id: string, status: string, title: string, priority = 2): string {
  return [id, status, String(priority), title].join('\t');
}

function writeDoc(dir: string, body: string): string {
  mkdirSync(dir, { recursive: true });
  const docPath = join(dir, 'gap-analysis.md');
  writeFileSync(docPath, `# Fixture gap analysis\n\n${body}\n`);
  return docPath;
}

const OPEN_A: FixtureBead = { id: 'fabric-aaaa0001', status: 'open', title: 'Open bug A', priority: 1 };
const CLOSED_B: FixtureBead = { id: 'fabric-bbbb0002', status: 'closed', title: 'Finished thing B', priority: 2 };
const OPEN_C: FixtureBead = { id: 'fabric-cccc0003', status: 'in_progress', title: 'Open hardening C', priority: 2 };

// Fixture temp dirs — removed after each test so nothing leaks to /tmp.
const tmpDirs: string[] = [];

function makeTmp(prefix: string): string {
  const dir = mkdtempSync(join(tmpdir(), prefix));
  tmpDirs.push(dir);
  return dir;
}

afterEach(() => {
  while (tmpDirs.length > 0) {
    const dir = tmpDirs.pop();
    if (dir) rmSync(dir, { recursive: true, force: true });
  }
});

describe('gap-inventory-check: --check', () => {
  let tmp: string;

  it('exits 0 and reports in sync when the inventory matches the store', async () => {
    tmp = makeTmp('gapinv-ok-');
    const checkpoint = join(tmp, 'checkpoint');
    writeCheckpoint(checkpoint, [OPEN_A, CLOSED_B, OPEN_C]);
    const doc = writeDoc(join(tmp, 'docs'), inventoryBlock([row(OPEN_A.id, 'open', OPEN_A.title, 1), row(OPEN_C.id, 'in_progress', OPEN_C.title)]));

    const res = await runScript(['--doc', doc, '--objects', checkpoint]);
    expect(res.code).toBe(0);
    expect(res.stdout).toContain('in sync');
  });

  it('exits 1 when the inventory lists a bead the store has closed (doc overstates)', async () => {
    tmp = makeTmp('gapinv-over-');
    const checkpoint = join(tmp, 'checkpoint');
    writeCheckpoint(checkpoint, [OPEN_A, CLOSED_B]);
    const doc = writeDoc(
      join(tmp, 'docs'),
      inventoryBlock([row(OPEN_A.id, 'open', OPEN_A.title, 1), row(CLOSED_B.id, 'open', CLOSED_B.title)]),
    );

    const res = await runScript(['--doc', doc, '--objects', checkpoint]);
    expect(res.code).toBe(1);
    expect(res.stderr).toContain('overstates');
    expect(res.stderr).toContain(CLOSED_B.id);
  });

  it('exits 1 when a store-open bead is missing from the inventory (doc understates)', async () => {
    tmp = makeTmp('gapinv-under-');
    const checkpoint = join(tmp, 'checkpoint');
    writeCheckpoint(checkpoint, [OPEN_A, CLOSED_B, OPEN_C]);
    const doc = writeDoc(join(tmp, 'docs'), inventoryBlock([row(OPEN_A.id, 'open', OPEN_A.title, 1)]));

    const res = await runScript(['--doc', doc, '--objects', checkpoint]);
    expect(res.code).toBe(1);
    expect(res.stderr).toContain('understates');
    expect(res.stderr).toContain(OPEN_C.id);
  });

  it('exits 1 when prose cites a bead id that does not exist in the store', async () => {
    tmp = makeTmp('gapinv-phantom-');
    const checkpoint = join(tmp, 'checkpoint');
    writeCheckpoint(checkpoint, [OPEN_A]);
    const doc = writeDoc(
      join(tmp, 'docs'),
      `Some prose citing phantom bead fabric-deadbeef.\n\n${inventoryBlock([row(OPEN_A.id, 'open', OPEN_A.title, 1)])}`,
    );

    const res = await runScript(['--doc', doc, '--objects', checkpoint]);
    expect(res.code).toBe(1);
    expect(res.stderr).toContain('fabric-deadbeef');
  });

  it('exits 2 when the document has no inventory block', async () => {
    tmp = makeTmp('gapinv-noblock-');
    const checkpoint = join(tmp, 'checkpoint');
    writeCheckpoint(checkpoint, [OPEN_A]);
    const doc = writeDoc(join(tmp, 'docs'), 'Prose only, no generated block.');

    const res = await runScript(['--doc', doc, '--objects', checkpoint]);
    expect(res.code).toBe(2);
    expect(res.stderr).toContain('inventory block missing');
  });

  it('exits 3 when no store source is available', async () => {
    tmp = makeTmp('gapinv-nostore-');
    const doc = writeDoc(join(tmp, 'docs'), inventoryBlock([]));

    const res = await runScript(['--doc', doc, '--objects', join(tmp, 'does-not-exist')]);
    // In a sandbox without the bead CLI on PATH this is 3; if the CLI answered,
    // the empty-inventory doc then drifts against the live store (exit 1).
    expect([1, 3]).toContain(res.code);
  });
});

describe('gap-inventory-check: --fix', () => {
  it('regenerates the inventory from the store and the document re-checks clean', async () => {
    const tmp = makeTmp('gapinv-fix-');
    const checkpoint = join(tmp, 'checkpoint');
    writeCheckpoint(checkpoint, [OPEN_A, CLOSED_B, OPEN_C]);
    const doc = writeDoc(
      join(tmp, 'docs'),
      inventoryBlock([row(OPEN_A.id, 'open', OPEN_A.title, 1), row(CLOSED_B.id, 'open', CLOSED_B.title)]),
    );

    const before = await runScript(['--doc', doc, '--objects', checkpoint]);
    expect(before.code).toBe(1);

    const fix = await runScript(['--fix', '--doc', doc, '--objects', checkpoint]);
    expect(fix.code).toBe(0);

    const rewritten = readFileSync(doc, 'utf8');
    expect(rewritten).toContain(OPEN_C.id);
    expect(rewritten).not.toContain(`${CLOSED_B.id}\topen`);

    const after = await runScript(['--doc', doc, '--objects', checkpoint]);
    expect(after.code).toBe(0);
    expect(after.stdout).toContain('in sync');
  });

  it('still exits 1 when prose citations are unfixable', async () => {
    const tmp = makeTmp('gapinv-fix2-');
    const checkpoint = join(tmp, 'checkpoint');
    writeCheckpoint(checkpoint, [OPEN_A]);
    const doc = writeDoc(
      join(tmp, 'docs'),
      `Prose citing phantom fabric-deadbeef.\n\n${inventoryBlock([])}`,
    );

    const fix = await runScript(['--fix', '--doc', doc, '--objects', checkpoint]);
    expect(fix.code).toBe(1);
    expect(fix.stderr).toContain('not auto-fixable');
  });
});

describe('gap-inventory-check: store loading', () => {
  it('falls back to the largest objects file when current.json is absent', async () => {
    const tmp = makeTmp('gapinv-fallback-');
    const checkpoint = join(tmp, 'checkpoint');
    const objectsDir = join(checkpoint, 'objects');
    mkdirSync(objectsDir, { recursive: true });
    // Newer generation (2 beads) vs older generation (stale status for A).
    writeFileSync(
      join(objectsDir, 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.jsonl'),
      `${JSON.stringify({ record_type: 'issue', issue: { id: OPEN_A.id, base_status: 'open', title: OPEN_A.title, priority: 1 } })}\n${JSON.stringify({ record_type: 'issue', issue: { id: CLOSED_B.id, base_status: 'closed', title: CLOSED_B.title, priority: 2 } })}\n`,
    );
    writeFileSync(
      join(objectsDir, 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.jsonl'),
      `${JSON.stringify({ record_type: 'issue', issue: { id: OPEN_A.id, base_status: 'closed', title: OPEN_A.title, priority: 1 } })}\n`,
    );
    const doc = writeDoc(join(tmp, 'docs'), inventoryBlock([row(OPEN_A.id, 'open', OPEN_A.title, 1)]));

    const res = await runScript(['--doc', doc, '--objects', checkpoint]);
    // A is open in the largest (newest) generation → inventory matches → in sync.
    expect(res.code).toBe(0);
    expect(res.stdout).toContain('in sync');
  });
});

describe('gap-inventory-check: real repository document (structural lint only)', () => {
  const realStoreAvailable =
    existsSync(join(REAL_CHECKPOINT, 'current.json')) || existsSync(join(REAL_CHECKPOINT, 'objects'));

  it('lints the committed gap-analysis document against the checkpoint', async () => {
    if (!realStoreAvailable) {
      // Bare checkouts without a checkpoint fall back to the bead CLI; if that is
      // absent too, there is nothing to lint against — skip rather than fail.
      console.warn('skipping: no bead checkpoint or CLI available');
      return;
    }
    const res = await runScript(['--lint-doc', '--doc', REAL_DOC, '--objects', REAL_CHECKPOINT]);
    if (res.code === 3) {
      console.warn('skipping: no store source available');
      return;
    }
    expect(res.code).toBe(0);
    expect(res.stdout).toContain('lint OK');
  });
});
