import React, { useState, useCallback } from 'react';
import {
  SessionDigestData,
  DigestTab,
  DigestBeadCompletion,
  DigestFileModification,
  DigestErrorOccurrence,
  DigestWorkerSummary,
  ErrorCategory,
} from '../types';

interface SessionDigestPanelProps {
  visible: boolean;
  onClose: () => void;
}

function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  if (ms < 60000) return `${(ms / 1000).toFixed(1)}s`;
  if (ms < 3600000) {
    const mins = Math.floor(ms / 60000);
    const secs = Math.floor((ms % 60000) / 1000);
    return `${mins}m ${secs}s`;
  }
  const hours = Math.floor(ms / 3600000);
  const mins = Math.floor((ms % 3600000) / 60000);
  return `${hours}h ${mins}m`;
}

function formatAsMarkdown(d: SessionDigestData): string {
  const lines: string[] = [];

  lines.push('# Session Digest');
  lines.push('');
  lines.push(`**Session ID:** ${d.sessionId}`);
  lines.push(`**Start Time:** ${new Date(d.startTime).toLocaleString()}`);
  lines.push(`**End Time:** ${new Date(d.endTime).toLocaleString()}`);
  lines.push(`**Duration:** ${formatDuration(d.durationMs)}`);
  lines.push('');

  lines.push('## Statistics');
  lines.push('');
  lines.push('| Metric | Value |');
  lines.push('|--------|-------|');
  lines.push(`| Total Events | ${d.stats.totalEvents} |`);
  lines.push(`| Total Workers | ${d.stats.totalWorkers} |`);
  lines.push(`| Total Beads | ${d.stats.totalBeads} |`);
  lines.push(`| Total Files | ${d.stats.totalFiles} |`);
  lines.push(`| Total Errors | ${d.stats.totalErrors} |`);
  lines.push('');

  if (d.cost.totalTokens > 0) {
    lines.push('## Cost Breakdown');
    lines.push('');
    lines.push(`- **Input Tokens:** ${d.cost.inputTokens.toLocaleString()}`);
    lines.push(`- **Output Tokens:** ${d.cost.outputTokens.toLocaleString()}`);
    lines.push(`- **Total Tokens:** ${d.cost.totalTokens.toLocaleString()}`);
    lines.push(`- **Estimated Cost:** $${d.cost.estimatedCostUsd.toFixed(4)}`);
    lines.push('');
  }

  lines.push('## Completed Beads');
  lines.push('');
  if (d.beadsCompleted.length === 0) {
    lines.push('_No beads completed_');
  } else {
    lines.push('| Bead ID | Worker | Completed At | Duration |');
    lines.push('|---------|--------|--------------|----------|');
    for (const bead of d.beadsCompleted) {
      const time = new Date(bead.completedAt).toLocaleString();
      const duration = bead.durationMs ? formatDuration(bead.durationMs) : '-';
      lines.push(`| ${bead.beadId} | ${bead.workerId.slice(0, 8)} | ${time} | ${duration} |`);
    }
  }
  lines.push('');

  lines.push('## Files Modified');
  lines.push('');
  if (d.filesModified.length === 0) {
    lines.push('_No files modified_');
  } else {
    lines.push('| Path | Modifications | Workers |');
    lines.push('|------|---------------|---------|');
    for (const file of d.filesModified) {
      lines.push(`| \`${file.path}\` | ${file.modifications} | ${file.workers.length} |`);
    }
  }
  lines.push('');

  lines.push('## Errors');
  lines.push('');
  if (d.errors.length === 0) {
    lines.push('_No errors encountered_');
  } else {
    lines.push('| Time | Category | Worker | Message |');
    lines.push('|------|----------|--------|---------|');
    for (const err of d.errors) {
      const time = new Date(err.timestamp).toLocaleTimeString();
      const msg = err.message.slice(0, 50).replace(/\n/g, ' ');
      lines.push(`| ${time} | ${err.category} | ${err.workerId.slice(0, 8)} | ${msg} |`);
    }
  }
  lines.push('');

  lines.push('## Worker Summary');
  lines.push('');
  lines.push('| Worker ID | Beads | Files | Errors | Active Time |');
  lines.push('|-----------|-------|-------|--------|-------------|');
  for (const worker of d.workers) {
    lines.push(`| ${worker.workerId.slice(0, 8)} | ${worker.beadsCompleted} | ${worker.filesModified} | ${worker.errorsEncountered} | ${formatDuration(worker.activeTimeMs)} |`);
  }
  lines.push('');

  lines.push('---');
  lines.push(`*Generated by FABRIC at ${new Date().toLocaleString()}*`);

  return lines.join('\n');
}

function formatAsText(d: SessionDigestData): string {
  const lines: string[] = [];

  lines.push('SESSION DIGEST');
  lines.push('='.repeat(50));
  lines.push('');
  lines.push(`Session ID: ${d.sessionId}`);
  lines.push(`Start Time: ${new Date(d.startTime).toLocaleString()}`);
  lines.push(`End Time: ${new Date(d.endTime).toLocaleString()}`);
  lines.push(`Duration: ${formatDuration(d.durationMs)}`);
  lines.push('');

  lines.push('STATISTICS');
  lines.push('-'.repeat(30));
  lines.push(`Total Events: ${d.stats.totalEvents}`);
  lines.push(`Total Workers: ${d.stats.totalWorkers}`);
  lines.push(`Total Beads: ${d.stats.totalBeads}`);
  lines.push(`Total Files: ${d.stats.totalFiles}`);
  lines.push(`Total Errors: ${d.stats.totalErrors}`);
  lines.push(`Avg Events/Worker: ${d.stats.avgEventsPerWorker.toFixed(1)}`);
  lines.push(`Avg Beads/Worker: ${d.stats.avgBeadsPerWorker.toFixed(1)}`);
  lines.push('');

  if (d.cost.totalTokens > 0) {
    lines.push('COST BREAKDOWN');
    lines.push('-'.repeat(30));
    lines.push(`Input Tokens: ${d.cost.inputTokens.toLocaleString()}`);
    lines.push(`Output Tokens: ${d.cost.outputTokens.toLocaleString()}`);
    lines.push(`Total Tokens: ${d.cost.totalTokens.toLocaleString()}`);
    lines.push(`Estimated Cost: $${d.cost.estimatedCostUsd.toFixed(4)}`);
    lines.push('');
  }

  lines.push('COMPLETED BEADS');
  lines.push('-'.repeat(30));
  for (const bead of d.beadsCompleted) {
    const time = new Date(bead.completedAt).toLocaleString();
    const duration = bead.durationMs ? ` (${formatDuration(bead.durationMs)})` : '';
    lines.push(`${bead.beadId} by ${bead.workerId.slice(0, 8)} at ${time}${duration}`);
  }
  if (d.beadsCompleted.length === 0) lines.push('No beads completed');
  lines.push('');

  lines.push('FILES MODIFIED');
  lines.push('-'.repeat(30));
  for (const file of d.filesModified) {
    lines.push(`${file.path} (${file.modifications} mods by ${file.workers.length} workers)`);
  }
  if (d.filesModified.length === 0) lines.push('No files modified');
  lines.push('');

  lines.push('ERRORS');
  lines.push('-'.repeat(30));
  for (const err of d.errors) {
    const time = new Date(err.timestamp).toLocaleTimeString();
    lines.push(`[${err.category.toUpperCase()}] ${time} ${err.workerId.slice(0, 8)}: ${err.message.slice(0, 100)}`);
  }
  if (d.errors.length === 0) lines.push('No errors encountered');
  lines.push('');

  lines.push('WORKER SUMMARY');
  lines.push('-'.repeat(30));
  for (const worker of d.workers) {
    lines.push(`${worker.workerId}`);
    lines.push(`  Beads: ${worker.beadsCompleted}  Files: ${worker.filesModified}  Errors: ${worker.errorsEncountered}  Events: ${worker.totalEvents}`);
    lines.push(`  Active: ${formatDuration(worker.activeTimeMs)}`);
  }
  if (d.workers.length === 0) lines.push('No workers');
  lines.push('');

  lines.push('---');
  lines.push(`Generated by FABRIC at ${new Date().toLocaleString()}`);

  return lines.join('\n');
}

function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ── Tab content renderers ────────────────────────────────────────────────────

const SummaryTab: React.FC<{ d: SessionDigestData }> = ({ d }) => (
  <div className="digest-tab-content">
    <div className="digest-section">
      <h4>Session Info</h4>
      <table className="digest-table">
        <tbody>
          <tr><td>Session ID</td><td className="digest-value">{d.sessionId}</td></tr>
          <tr><td>Start Time</td><td className="digest-value">{new Date(d.startTime).toLocaleString()}</td></tr>
          <tr><td>End Time</td><td className="digest-value">{new Date(d.endTime).toLocaleString()}</td></tr>
          <tr><td>Duration</td><td className="digest-value">{formatDuration(d.durationMs)}</td></tr>
        </tbody>
      </table>
    </div>

    <div className="digest-section">
      <h4>Statistics</h4>
      <table className="digest-table">
        <tbody>
          <tr><td>Total Events</td><td className="digest-value">{d.stats.totalEvents.toLocaleString()}</td></tr>
          <tr><td>Total Workers</td><td className="digest-value">{d.stats.totalWorkers}</td></tr>
          <tr><td>Total Beads</td><td className="digest-value">{d.stats.totalBeads}</td></tr>
          <tr><td>Total Files</td><td className="digest-value">{d.stats.totalFiles}</td></tr>
          <tr><td>Total Errors</td><td className="digest-value digest-error">{d.stats.totalErrors}</td></tr>
          <tr><td>Avg Events/Worker</td><td className="digest-value">{d.stats.avgEventsPerWorker.toFixed(1)}</td></tr>
          <tr><td>Avg Beads/Worker</td><td className="digest-value">{d.stats.avgBeadsPerWorker.toFixed(1)}</td></tr>
        </tbody>
      </table>
    </div>

    {d.cost.totalTokens > 0 && (
      <div className="digest-section">
        <h4>Cost Breakdown</h4>
        <table className="digest-table">
          <tbody>
            <tr><td>Input Tokens</td><td className="digest-value">{d.cost.inputTokens.toLocaleString()}</td></tr>
            <tr><td>Output Tokens</td><td className="digest-value">{d.cost.outputTokens.toLocaleString()}</td></tr>
            <tr><td>Total Tokens</td><td className="digest-value">{d.cost.totalTokens.toLocaleString()}</td></tr>
            <tr><td>Estimated Cost</td><td className="digest-value digest-cost">${d.cost.estimatedCostUsd.toFixed(4)}</td></tr>
          </tbody>
        </table>
      </div>
    )}

    <div className="digest-section">
      <h4>Completed Work</h4>
      <div className="digest-summary-row">
        <span className="digest-badge digest-badge-green">{d.beadsCompleted.length} beads</span>
        <span className="digest-badge digest-badge-cyan">{d.filesModified.length} files</span>
        <span className="digest-badge digest-badge-default">{d.workers.length} workers</span>
        {d.errors.length > 0 && <span className="digest-badge digest-badge-red">{d.errors.length} errors</span>}
      </div>
    </div>
  </div>
);

const BeadsTab: React.FC<{ beads: DigestBeadCompletion[] }> = ({ beads }) => {
  if (beads.length === 0) {
    return <div className="digest-empty">No beads completed in this session</div>;
  }
  const sorted = [...beads].sort((a, b) => b.completedAt - a.completedAt);
  return (
    <div className="digest-tab-content">
      <table className="digest-data-table">
        <thead>
          <tr>
            <th>Bead ID</th>
            <th>Worker</th>
            <th>Completed At</th>
            <th>Duration</th>
          </tr>
        </thead>
        <tbody>
          {sorted.map((bead, i) => (
            <tr key={i}>
              <td className="digest-mono digest-purple">{bead.beadId}</td>
              <td className="digest-mono digest-cyan">{bead.workerId.slice(0, 8)}</td>
              <td>{new Date(bead.completedAt).toLocaleTimeString()}</td>
              <td>{bead.durationMs ? formatDuration(bead.durationMs) : '-'}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

const FilesTab: React.FC<{ files: DigestFileModification[] }> = ({ files }) => {
  if (files.length === 0) {
    return <div className="digest-empty">No files modified in this session</div>;
  }
  const sorted = [...files].sort((a, b) => b.modifications - a.modifications);
  return (
    <div className="digest-tab-content">
      <table className="digest-data-table">
        <thead>
          <tr>
            <th>Path</th>
            <th>Mods</th>
            <th>Workers</th>
            <th>Tools</th>
          </tr>
        </thead>
        <tbody>
          {sorted.map((file, i) => {
            const heat = file.modifications >= 10 ? 'digest-red'
              : file.modifications >= 5 ? 'digest-yellow'
              : file.modifications >= 3 ? 'digest-cyan'
              : 'digest-green';
            return (
              <tr key={i}>
                <td className="digest-mono digest-path">{file.path}</td>
                <td className={`digest-count ${heat}`}>{file.modifications}</td>
                <td>{file.workers.length}</td>
                <td className="digest-muted">{file.tools.join(', ')}</td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
};

const ErrorsTab: React.FC<{ errors: DigestErrorOccurrence[] }> = ({ errors }) => {
  if (errors.length === 0) {
    return <div className="digest-empty digest-success">No errors encountered in this session</div>;
  }
  const sorted = [...errors].sort((a, b) => b.timestamp - a.timestamp);
  return (
    <div className="digest-tab-content">
      {sorted.map((err, i) => (
        <div key={i} className="digest-error-card">
          <div className="digest-error-header">
            <span className="digest-error-category">[{err.category.toUpperCase()}]</span>
            <span className="digest-muted">{new Date(err.timestamp).toLocaleTimeString()}</span>
            <span className="digest-cyan">{err.workerId.slice(0, 8)}</span>
          </div>
          <div className="digest-error-message">
            {err.message.slice(0, 200)}{err.message.length > 200 ? '...' : ''}
          </div>
          {err.fingerprint && (
            <div className="digest-fingerprint">fp: {err.fingerprint}</div>
          )}
        </div>
      ))}
    </div>
  );
};

const WorkersTab: React.FC<{ workers: DigestWorkerSummary[] }> = ({ workers }) => {
  if (workers.length === 0) {
    return <div className="digest-empty">No workers in this session</div>;
  }
  const sorted = [...workers].sort((a, b) => b.beadsCompleted - a.beadsCompleted);
  return (
    <div className="digest-tab-content">
      {sorted.map((worker, i) => (
        <div key={i} className="digest-worker-card">
          <div className="digest-worker-id">{worker.workerId}</div>
          <div className="digest-worker-stats">
            <span><strong>Beads:</strong> <span className="digest-green">{worker.beadsCompleted}</span></span>
            <span><strong>Files:</strong> {worker.filesModified}</span>
            <span><strong>Errors:</strong> <span className="digest-error">{worker.errorsEncountered}</span></span>
            <span><strong>Events:</strong> {worker.totalEvents}</span>
            <span><strong>Active:</strong> {formatDuration(worker.activeTimeMs)}</span>
          </div>
          <div className="digest-worker-time">
            <span className="digest-muted">
              {new Date(worker.firstActivity).toLocaleTimeString()} – {new Date(worker.lastActivity).toLocaleTimeString()}
            </span>
          </div>
        </div>
      ))}
    </div>
  );
};

// ── Main Component ────────────────────────────────────────────────────────────

const TABS: Array<{ key: DigestTab; label: string }> = [
  { key: 'summary', label: 'Summary' },
  { key: 'beads', label: 'Beads' },
  { key: 'files', label: 'Files' },
  { key: 'errors', label: 'Errors' },
  { key: 'workers', label: 'Workers' },
];

const SessionDigestPanel: React.FC<SessionDigestPanelProps> = ({ visible, onClose }) => {
  const [digest, setDigest] = useState<SessionDigestData | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<DigestTab>('summary');
  const [exportStatus, setExportStatus] = useState<string | null>(null);

  const generateDigest = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch('/api/digest');
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const data: SessionDigestData = await res.json();
      setDigest(data);
      setActiveTab('summary');
    } catch (err) {
      setError(String(err));
    } finally {
      setLoading(false);
    }
  }, []);

  const handleExport = useCallback((format: 'json' | 'markdown' | 'text') => {
    if (!digest) return;
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const base = `session-digest-${timestamp}`;

    let content: string;
    let filename: string;
    let mime: string;

    switch (format) {
      case 'json':
        content = JSON.stringify(digest, null, 2);
        filename = `${base}.json`;
        mime = 'application/json';
        break;
      case 'markdown':
        content = formatAsMarkdown(digest);
        filename = `${base}.md`;
        mime = 'text/markdown';
        break;
      case 'text':
        content = formatAsText(digest);
        filename = `${base}.txt`;
        mime = 'text/plain';
        break;
    }

    downloadFile(content, filename, mime);
    setExportStatus(`Exported ${filename}`);
    setTimeout(() => setExportStatus(null), 3000);
  }, [digest]);

  if (!visible) return null;

  return (
    <div className="digest-panel">
      <div className="digest-header">
        <h3>Session Digest</h3>
        <div className="digest-header-actions">
          <button
            className="digest-generate-btn"
            onClick={generateDigest}
            disabled={loading}
          >
            {loading ? 'Generating...' : 'Generate Digest'}
          </button>
          <button className="close-button" onClick={onClose}>×</button>
        </div>
      </div>

      {error && (
        <div className="digest-fetch-error">Failed to generate digest: {error}</div>
      )}

      {!digest && !loading && !error && (
        <div className="digest-placeholder">
          <p>Click <strong>Generate Digest</strong> to summarize the current session.</p>
        </div>
      )}

      {digest && (
        <>
          <div className="digest-meta">
            <span><strong>Session:</strong> {digest.sessionId.slice(0, 20)}…</span>
            <span><strong>Duration:</strong> {formatDuration(digest.durationMs)}</span>
            <span><strong>Events:</strong> {digest.stats.totalEvents.toLocaleString()}</span>
            <span><strong>Workers:</strong> {digest.stats.totalWorkers}</span>
          </div>

          <div className="digest-tabs">
            {TABS.map(tab => (
              <button
                key={tab.key}
                className={`digest-tab ${activeTab === tab.key ? 'active' : ''}`}
                onClick={() => setActiveTab(tab.key)}
              >
                {tab.label}
                {tab.key === 'errors' && digest.errors.length > 0 && (
                  <span className="digest-tab-badge">{digest.errors.length}</span>
                )}
                {tab.key === 'beads' && digest.beadsCompleted.length > 0 && (
                  <span className="digest-tab-badge digest-tab-badge-green">{digest.beadsCompleted.length}</span>
                )}
              </button>
            ))}
          </div>

          <div className="digest-content">
            {activeTab === 'summary' && <SummaryTab d={digest} />}
            {activeTab === 'beads' && <BeadsTab beads={digest.beadsCompleted} />}
            {activeTab === 'files' && <FilesTab files={digest.filesModified} />}
            {activeTab === 'errors' && <ErrorsTab errors={digest.errors} />}
            {activeTab === 'workers' && <WorkersTab workers={digest.workers} />}
          </div>

          <div className="digest-footer">
            <div className="digest-export-buttons">
              <span className="digest-export-label">Export:</span>
              <button className="digest-export-btn" onClick={() => handleExport('json')}>JSON</button>
              <button className="digest-export-btn" onClick={() => handleExport('markdown')}>Markdown</button>
              <button className="digest-export-btn" onClick={() => handleExport('text')}>Text</button>
            </div>
            {exportStatus && <span className="digest-export-status">{exportStatus}</span>}
          </div>
        </>
      )}
    </div>
  );
};

export default SessionDigestPanel;
